zabbix_version: 6.0
db_password: zabbix@dicz7
db_user: zabbix
db_name: zabbix
sql_script_path: /usr/share/zabbix-sql-scripts/postgresql/server.sql.gz
# zabbix_web_user: "Admin"
# zabbix_web_password: "dic72"

